### ISSUE TITLE
Can you add a License file

### ISSUE THREAD

**Issue by malisipi** [xjunko/v-mpv#1]
I think this project is very useful for gg and ui kits. Please add a license to make embeddable into applications.

**Comment by malisipi** [comment]
Also having a license, allows the forks and contribution legally.

**Comment by xjunko** [comment]
Alright, I forgot to do this yesterday :+1:

**Comment by malisipi** [comment]
@xjunko Does this project licensed with GPLv2-only or GPLv2-or-later? If the license was GPLv2-or-later, this project code will be usable with GPLv3. And most software is using GPLv3 and this is very important for mixing with the already written codebase.

Also i'm glad for fast response. Thanks for your attention.

**Comment by xjunko** [comment]
> @xjunko Does this project licensed with GPLv2-only or GPLv2-or-later? If the license was GPLv2-or-later, this project code will be usable with GPLv3. And most software is using GPLv3 and this is very important for mixing with the already written codebase.
> 
> Also i'm glad for fast response. Thanks for your attention.

Wait I didn't notice there was a GPLv3, should I change to that instead?
It was supposed to be `GPLv2-or-later` by the way.

**Comment by malisipi** [comment]
You can switch if you want. Since GPLv2 and GPLv3 are not compatible, so i recommend. Also if you want you can license it with LGPL. LGPL is a library license that require only-library changes must be open-source.

PS: I am not a lawyer. This is not legal advice.

**Comment by xjunko** [comment]
Alrighty, GPLv3 it is then. I'm not sure about LGPL but I'll keep that in mind!

**Comment by xjunko** [comment]
Done :+1:
