### ISSUE TITLE
Can you license it LGPLv3?

### ISSUE THREAD

**Issue by malisipi** [xjunko/v-mpv#5]
I made a video player module for MUI. However the module is containing some codebase from this codebase and GPLv3 is forcing to use same license. So any application that use the module must be GPLv3. Can you dual-license or relicense the application with LGPLv3?

Thanks for interest.

**Comment by xjunko** [comment]
Well, I'm not against it. I'm making it dual-licensed (GPL3 & LGPL3). Sounds good?
#6

**Comment by malisipi** [comment]
I'm really thank you! ❤️

**Comment by xjunko** [comment]
I take that as a yes. Merged.
